"""implement alter ego personas

Revision ID: 714815d2aa28
Revises: 9e49bfbda36c
Create Date: 2026-03-21 19:58:57.229598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '714815d2aa28'
down_revision: Union[str, Sequence[str], None] = '9e49bfbda36c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 1. Сначала создаем таблицу personas
    op.create_table('personas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('avatar_path', sa.String(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_personas_id'), 'personas', ['id'], unique=False)
    op.create_index(op.f('ix_personas_username'), 'personas', ['username'], unique=True)
    
    # 2. Добавляем колонку persona_id в hobbies (пока nullable=True для миграции данных)
    op.add_column('hobbies', sa.Column('persona_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(), nullable=True))

    # 3. Переносим данные: Для каждого пользователя создаем дефолтную Персону
    # Это критический шаг, чтобы не потерять авторов старых постов
    connection = op.get_bind()
    
    # Получаем старых юзеров
    users = connection.execute(sa.text("SELECT id, username FROM users")).fetchall()
    for user in users:
        # Создаем персону
        connection.execute(
            sa.text("INSERT INTO personas (user_id, username, is_default) VALUES (:user_id, :username, true)"),
            {"user_id": user[0], "username": user[1]}
        )
        # Получаем ID только что созданной персоны
        persona_id = connection.execute(
            sa.text("SELECT id FROM personas WHERE user_id = :user_id"),
            {"user_id": user[0]}
        ).scalar()
        
        # Обновляем все хобби этого юзера, привязывая их к новой персоне
        connection.execute(
            sa.text("UPDATE hobbies SET persona_id = :persona_id WHERE author_id = :user_id"),
            {"persona_id": persona_id, "user_id": user[0]}
        )

    # 4. Теперь, когда данные перенесены, делаем колонку persona_id обязательной
    op.alter_column('hobbies', 'persona_id', existing_type=sa.Integer(), nullable=False)

    # 5. Убираем старые связи
    op.drop_constraint('hobbies_author_id_fkey', 'hobbies', type_='foreignkey')
    op.create_foreign_key(None, 'hobbies', 'personas', ['persona_id'], ['id'])
    op.drop_column('hobbies', 'author_id')
    op.drop_column('hobbies', 'author')
    
    op.drop_index('ix_users_username', table_name='users')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_index('ix_users_username', 'users', ['username'], unique=True)
    op.drop_column('users', 'deleted_at')
    op.add_column('hobbies', sa.Column('author', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('hobbies', sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'hobbies', type_='foreignkey')
    op.create_foreign_key('hobbies_author_id_fkey', 'hobbies', 'users', ['author_id'], ['id'])
    op.drop_column('hobbies', 'persona_id')
    op.drop_index(op.f('ix_personas_username'), table_name='personas')
    op.drop_index(op.f('ix_personas_id'), table_name='personas')
    op.drop_table('personas')
    # ### end Alembic commands ###
