"""add_persona_follows

Revision ID: d77ba3ee9cd9
Revises: 46771b7f2507
Create Date: 2026-03-30 19:28:49.088380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd77ba3ee9cd9'
down_revision: Union[str, Sequence[str], None] = '46771b7f2507'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follows',
    sa.Column('follower_persona_id', sa.Integer(), nullable=False),
    sa.Column('followed_persona_id', sa.Integer(), nullable=False),
    sa.Column('follower_user_id', sa.Integer(), nullable=False),
    sa.Column('followed_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['followed_persona_id'], ['personas.id'], ),
    sa.ForeignKeyConstraint(['followed_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['follower_persona_id'], ['personas.id'], ),
    sa.ForeignKeyConstraint(['follower_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('follower_persona_id', 'followed_persona_id')
    )
    op.create_index(op.f('ix_follows_followed_user_id'), 'follows', ['followed_user_id'], unique=False)
    op.create_index(op.f('ix_follows_follower_user_id'), 'follows', ['follower_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_follows_follower_user_id'), table_name='follows')
    op.drop_index(op.f('ix_follows_followed_user_id'), table_name='follows')
    op.drop_table('follows')
    # ### end Alembic commands ###
